"""changed_disabled_to_active

Revision ID: 8b9630297535
Revises: ad7b559651a4
Create Date: 2026-05-03 17:04:20.093258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b9630297535'
down_revision: Union[str, Sequence[str], None] = 'ad7b559651a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
